services:
  exporter:
    container_name: exporter
    hostname: exporter
    image: masgeek/fuelrod-exporter:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app