[supervisord]
nodaemon=false
logfile=/var/log/fuelrod/supervisord.log
loglevel=info
pidfile=/var/run/supervisord.pid

[program:dramatiq_worker]
command=bash -c "dramatiq fuelrod_exporter.tasks --processes ${DRAMATIQ_PROCESSES:-1} --threads ${DRAMATIQ_THREADS:-2}"
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/fuelrod/worker.err.log
stdout_logfile=/var/log/fuelrod/worker.out.log
environment=DRAMATIQ_PROCESSES="1",DRAMATIQ_THREADS="2"
user=fuelrod