[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=info
pidfile=/tmp/supervisord.pid

[program:dramatiq_worker]
command=bash -c "dramatiq fuelrod_exporter.tasks.export_tasks --processes ${DRAMATIQ_PROCESSES:-1} --threads ${DRAMATIQ_THREADS:-2}"
autostart=true
autorestart=true
stderr_logfile=/var/log/worker.err.log
stdout_logfile=/var/log/worker.out.log
environment=DRAMATIQ_PROCESSES="1",DRAMATIQ_THREADS="2"
user=root
