[supervisord]
nodaemon=false
user=root
logfile=/app/logs/supervisord.log
loglevel=debug
pidfile=/var/run/supervisord.pid

[include]
files = /etc/supervisor/conf.d/*.conf

[program:dramatiq_worker]
command=bash -c "dramatiq fuelrod_exporter.tasks --processes ${DRAMATIQ_PROCESSES:-1} --threads ${DRAMATIQ_THREADS:-2}"
autostart=true
autorestart=true
startretries=3
stderr_logfile=/app/logs/worker.err.log
stdout_logfile=/app/logs/worker.out.log
environment=DRAMATIQ_PROCESSES="1",DRAMATIQ_THREADS="2"