"""
AUTO-GENERATED ORM MODELS DO NOT EDIT!!!
This file was generated by sqlacodegen.
Schema is dynamically injected at runtime using DB_SCHEMA.
"""

import os
import sys
import subprocess
import fnmatch
from pathlib import Path
from typing import List, Optional, Dict, Tuple

from dotenv import load_dotenv
from loguru import logger
from sqlalchemy import create_engine, MetaData, inspect
from sqlalchemy.exc import SQLAlchemyError

# Load environment variables from .env file
load_dotenv()


# Configure logging based on environment variables
def configure_logging():
    """Configure loguru logger based on environment variables."""
    # Remove default handler first
    logger.remove()

    # Get logging configuration from environment
    log_level = os.getenv("LOG_LEVEL", "INFO").upper()
    log_format = os.getenv("LOG_FORMAT", "default")
    log_file = os.getenv("LOG_FILE")
    log_rotation = os.getenv("LOG_ROTATION", "10 MB")
    log_retention = os.getenv("LOG_RETENTION", "7 days")
    log_json = os.getenv("LOG_JSON", "false").lower() == "true"

    # Define format templates
    formats = {
        "default": "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>",
        "detailed": "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> | <level>{message}</level>",
        "simple": "<level>{level}: {message}</level>",
        "minimal": "{message}",
        "json": None  # Will use serialize=True for JSON format
    }

    # Use JSON format if requested, otherwise use the specified format
    if log_json:
        format_str = formats.get(log_format, formats["default"])
        serialize = True
    else:
        format_str = formats.get(log_format, formats["default"])
        serialize = False

    # Add console handler
    logger.add(
        sink=sys.stderr,
        level=log_level,
        format=format_str,
        colorize=not log_json,
        serialize=serialize
    )

    # Add file handler if specified
    if log_file:
        logger.add(
            sink=log_file,
            level=log_level,
            format=format_str,
            rotation=log_rotation,
            retention=log_retention,
            serialize=serialize,
            colorize=False  # No colors in log files
        )

    logger.debug(f"Logging configured - Level: {log_level}, Format: {log_format}, JSON: {log_json}, File: {log_file}")


# Initialize logging
configure_logging()

BASE_HEADER = '''"""
AUTO-GENERATED ORM MODELS DO NOT EDIT!!!
This file was generated by sqlacodegen.
Schema is dynamically injected at runtime using DB_SCHEMA.
"""

import os
from sqlalchemy.orm import declarative_base
from sqlalchemy import MetaData

def make_base(schema: str):
    metadata = MetaData(schema=schema)
    return declarative_base(metadata=metadata)

DB_SCHEMA = os.getenv("DB_SCHEMA", "public")
Base = make_base(DB_SCHEMA)

'''

VIEW_HEADER = '''"""
AUTO-GENERATED ORM VIEW MODELS DO NOT EDIT!!!
This file was generated by sqlacodegen.
Schema is dynamically injected at runtime using DB_SCHEMA.
"""

import os
from sqlalchemy.orm import declarative_base
from sqlalchemy import MetaData

def make_base(schema: str):
    metadata = MetaData(schema=schema)
    return declarative_base(metadata=metadata)

DB_SCHEMA = os.getenv("DB_SCHEMA", "public")
Base = make_base(DB_SCHEMA)

'''


class ORMGeneratorError(Exception):
    """Custom exception for ORM generation errors."""
    pass


def create_dummy_file(filepath: Path, header: str = BASE_HEADER) -> None:
    """Create a dummy file with placeholder content."""
    filepath.parent.mkdir(parents=True, exist_ok=True)

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(header)
            f.write("# Replace this content with generated ORM code\n")
        logger.info(f"Dummy file created at {filepath}")
    except OSError as e:
        raise ORMGeneratorError(f"Failed to create dummy file at {filepath}: {e}") from e


def get_database_objects(db_url: str, schema: Optional[str] = None) -> Dict[str, List[str]]:
    """Retrieve tables and views from the database schema."""
    try:
        engine = create_engine(db_url)
        inspector = inspect(engine)

        # Get tables
        tables = inspector.get_table_names(schema=schema)

        # Get views
        views = inspector.get_view_names(schema=schema)

        logger.debug(f"Tables in schema '{schema or 'default'}': {tables}")
        logger.debug(f"Views in schema '{schema or 'default'}': {views}")

        return {
            "tables": tables,
            "views": views
        }
    except SQLAlchemyError as e:
        raise ORMGeneratorError(f"Failed to connect to database or inspect schema: {e}") from e


def parse_comma_separated_env(env_var: str, default: str = "") -> List[str]:
    """Parse comma-separated environment variable into a list of stripped strings."""
    value = os.getenv(env_var, default)
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def filter_objects(all_objects: List[str], excluded_patterns: List[str], included_objects: List[str] = None) -> List[
    str]:
    """
    Filter database objects based on exclusion patterns and explicit inclusions using wildcard matching.

    Supports Unix shell-style wildcards:
    - * matches everything
    - ? matches any single character
    - [seq] matches any character in seq
    - [!seq] matches any character not in seq

    Examples:
    - "temp_*" excludes all objects starting with "temp_"
    - "*_backup" excludes all objects ending with "_backup"
    - "test_table_?" excludes test_table_1, test_table_2, etc.
    """
    if included_objects is None:
        included_objects = []

    # Start with all objects
    filtered_objects = list(all_objects)
    excluded_objects = []

    # Apply exclusion patterns
    if excluded_patterns:
        temp_filtered = []
        for obj in filtered_objects:
            is_excluded = False
            for pattern in excluded_patterns:
                if fnmatch.fnmatch(obj, pattern):
                    logger.debug(f"Object '{obj}' excluded by pattern '{pattern}'")
                    is_excluded = True
                    excluded_objects.append((obj, pattern))
                    break

            if not is_excluded:
                temp_filtered.append(obj)

        filtered_objects = temp_filtered

    # Add explicitly included objects (even if they were excluded by patterns)
    for obj in included_objects:
        if obj not in filtered_objects and obj in all_objects:
            filtered_objects.append(obj)
            logger.debug(f"Object '{obj}' explicitly included")

    # Remove duplicates while preserving order
    filtered_objects = list(dict.fromkeys(filtered_objects))

    logger.info(
        f"Object filtering results: {len(filtered_objects)} included, {len(excluded_objects)} excluded from {len(all_objects)} total")

    if excluded_objects:
        logger.debug("Excluded objects details:")
        for obj, pattern in excluded_objects:
            logger.debug(f"  - '{obj}' (pattern: '{pattern}')")

    return filtered_objects


def validate_environment() -> dict:
    """Validate required environment variables and return configuration."""
    db_url = os.getenv("DB_URL")
    if not db_url:
        raise ORMGeneratorError("DB_URL environment variable is not set")

    # Table configuration
    excluded_table_patterns = parse_comma_separated_env("EXCLUDED_TABLES", "spatial_ref_sys,alembic_version")
    included_tables = parse_comma_separated_env("INCLUDED_TABLES")

    # View configuration
    excluded_view_patterns = parse_comma_separated_env("EXCLUDED_VIEWS")
    included_views = parse_comma_separated_env("INCLUDED_VIEWS")

    # File paths
    base_outfile_path = Path(os.getenv("OUTFILE_PATH", "src/fuelrod_exporter/models/fuelrod.py"))

    # Generate view file path by replacing the filename
    view_outfile_path = base_outfile_path.parent / f"{base_outfile_path.stem}_views{base_outfile_path.suffix}"

    config = {
        "db_url": db_url,
        "outfile_path": base_outfile_path,
        "view_outfile_path": view_outfile_path,
        "excluded_tables": excluded_table_patterns,
        "included_tables": included_tables,
        "excluded_views": excluded_view_patterns,
        "included_views": included_views,
        "generator": os.getenv("GENERATOR", "declarative"),
        "schema": os.getenv("DB_SCHEMA"),  # Optional schema specification
        "generate_views": os.getenv("GENERATE_VIEWS", "true").lower() == "true"
    }

    logger.info("Configuration loaded:")
    logger.info(f"  - Database URL: {db_url[:20]}...")  # Truncate for security
    logger.info(f"  - Tables output file: {config['outfile_path']}")
    logger.info(f"  - Views output file: {config['view_outfile_path']}")
    logger.info(f"  - Excluded table patterns: {excluded_table_patterns}")
    logger.info(f"  - Included tables: {included_tables}")
    logger.info(f"  - Excluded view patterns: {excluded_view_patterns}")
    logger.info(f"  - Included views: {included_views}")
    logger.info(f"  - Generator: {config['generator']}")
    logger.info(f"  - Schema: {config['schema'] or 'default'}")
    logger.info(f"  - Generate views: {config['generate_views']}")

    return config


def run_sqlacodegen_command(config: dict, objects_to_include: List[str], output_path: Path) -> None:
    """Execute the sqlacodegen command with proper error handling."""
    command = [
        "sqlacodegen",
        config["db_url"],
        "--outfile", str(output_path),
        "--generator", config["generator"],
        "--tables", ",".join(objects_to_include),
    ]

    # Add schema if specified
    # if config["schema"]:
    #     command.extend(["--schema", config["schema"]])

    logger.debug(f"Executing command: {' '.join(command)}")

    try:
        result = subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True,
            timeout=300  # 5-minute timeout
        )

        if result.stdout:
            logger.debug(f"sqlacodegen stdout: {result.stdout}")
        if result.stderr:
            logger.warning(f"sqlacodegen stderr: {result.stderr}")

    except subprocess.CalledProcessError as e:
        error_msg = f"sqlacodegen failed with exit code {e.returncode}"
        if e.stderr:
            error_msg += f": {e.stderr}"
        raise ORMGeneratorError(error_msg) from e
    except subprocess.TimeoutExpired as e:
        raise ORMGeneratorError("sqlacodegen command timed out after 5 minutes") from e


def strip_sqlacodegen_header(filepath: Path) -> None:
    """Remove sqlacodegen's autogenerated Base class and header."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            lines = f.readlines()

        start_idx = 0
        for i, line in enumerate(lines):
            # stop at first model class, skip the autogenerated Base
            if line.strip().startswith("class ") and not line.strip().startswith("class Base"):
                start_idx = i
                break

        with open(filepath, "w", encoding="utf-8") as f:
            f.writelines(lines[start_idx:])

        logger.info(f"Stripped sqlacodegen Base/header from {filepath}")
    except OSError as e:
        raise ORMGeneratorError(f"Failed to strip header: {e}") from e


def prepend_header_to_file(filepath: Path, header: str = BASE_HEADER) -> None:
    """Prepend the specified header to the generated file."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(header + content)

        logger.info(f"Header prepended to {filepath}")
    except OSError as e:
        raise ORMGeneratorError(f"Failed to prepend header to {filepath}: {e}") from e


def generate_init_file(models_dir: Path, table_file: str, view_file: str = None) -> None:
    """Generate __init__.py file to export all models."""
    init_path = models_dir / "__init__.py"

    try:
        init_content = f'''"""
Auto-generated models package.
"""

from .{Path(table_file).stem} import *

'''

        if view_file:
            init_content += f"from .{Path(view_file).stem} import *\n"

        with open(init_path, "w", encoding="utf-8") as f:
            f.write(init_content)

        logger.info(f"Generated __init__.py at {init_path}")
    except OSError as e:
        raise ORMGeneratorError(f"Failed to create __init__.py: {e}") from e


def run_sqlacodegen() -> None:
    """
    Run sqlacodegen to generate model classes with comprehensive error handling.
    Separates tables and views into different files.
    """
    try:
        # Validate environment and get configuration
        config = validate_environment()

        # Get all database objects
        db_objects = get_database_objects(config["db_url"], config["schema"])
        all_tables = db_objects["tables"]
        all_views = db_objects["views"]

        if not all_tables and not all_views:
            logger.warning("No tables or views found in the database schema")
            return

        # Filter tables based on exclusion patterns and inclusions
        included_tables = filter_objects(
            all_tables,
            config["excluded_tables"],
            config["included_tables"]
        )

        # Filter views based on exclusion patterns and inclusions
        included_views = []
        if config["generate_views"] and all_views:
            included_views = filter_objects(
                all_views,
                config["excluded_views"],
                config["included_views"]
            )

        # Generate tables file
        if included_tables:
            logger.info(f"Generating table models for {len(included_tables)} tables: {included_tables}")

            # Create dummy file first
            create_dummy_file(config["outfile_path"], BASE_HEADER)

            # Run sqlacodegen for tables
            run_sqlacodegen_command(config, included_tables, config["outfile_path"])

            # Prepend header to generated file
            prepend_header_to_file(config["outfile_path"], BASE_HEADER)

            logger.success(f"Table models generated successfully at {config['outfile_path']}")
        else:
            logger.warning("No tables to generate after filtering")

        # Generate views file
        if included_views:
            logger.info(f"Generating view models for {len(included_views)} views: {included_views}")

            # Create dummy file first
            create_dummy_file(config["view_outfile_path"], VIEW_HEADER)

            # Run sqlacodegen for views
            run_sqlacodegen_command(config, included_views, config["view_outfile_path"])

            # Prepend header to generated file
            prepend_header_to_file(config["view_outfile_path"], VIEW_HEADER)

            logger.success(f"View models generated successfully at {config['view_outfile_path']}")
        else:
            if config["generate_views"]:
                logger.warning("No views to generate after filtering")
            else:
                logger.info("View generation disabled")

        # Generate __init__.py file
        if included_tables or included_views:
            models_dir = config["outfile_path"].parent
            table_file = config["outfile_path"].name if included_tables else None
            view_file = config["view_outfile_path"].name if included_views else None

            if table_file:  # Only generate init if we have at least tables
                generate_init_file(models_dir, table_file, view_file)

        logger.success("ORM model generation completed successfully!")

    except Exception as e:
        logger.error(f"Unexpected error during ORM generation: {e}")
        raise ORMGeneratorError(f"Unexpected error: {e}") from e


def main():
    try:
        run_sqlacodegen()
    except ORMGeneratorError:
        exit(1)
    except KeyboardInterrupt:
        logger.info("Operation cancelled by user")
        exit(130)


if __name__ == "__main__":
    main()
