"""
AUTO-GENERATED ORM MODELS DO NOT EDIT!!!
This file was generated by sqlacodegen.
Schema is dynamically injected at runtime using DB_SCHEMA.
"""

import os
import sys
import subprocess
import fnmatch
from pathlib import Path
from typing import List, Optional

from dotenv import load_dotenv
from loguru import logger
from sqlalchemy import create_engine, MetaData
from sqlalchemy.exc import SQLAlchemyError

# Load environment variables from .env file
load_dotenv()

# Configure logging based on environment variables
def configure_logging():
    """Configure loguru logger based on environment variables."""
    # Remove default handler first
    logger.remove()

    # Get logging configuration from environment
    log_level = os.getenv("LOG_LEVEL", "INFO").upper()
    log_format = os.getenv("LOG_FORMAT", "default")
    log_file = os.getenv("LOG_FILE")
    log_rotation = os.getenv("LOG_ROTATION", "10 MB")
    log_retention = os.getenv("LOG_RETENTION", "7 days")
    log_json = os.getenv("LOG_JSON", "false").lower() == "true"

    # Define format templates
    formats = {
        "default": "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>",
        "detailed": "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> | <level>{message}</level>",
        "simple": "<level>{level}: {message}</level>",
        "minimal": "{message}",
        "json": None  # Will use serialize=True for JSON format
    }

    # Use JSON format if requested, otherwise use the specified format
    if log_json:
        format_str = formats.get(log_format, formats["default"])
        serialize = True
    else:
        format_str = formats.get(log_format, formats["default"])
        serialize = False

    # Add console handler
    logger.add(
        sink=sys.stderr,
        level=log_level,
        format=format_str,
        colorize=not log_json,
        serialize=serialize
    )

    # Add file handler if specified
    if log_file:
        logger.add(
            sink=log_file,
            level=log_level,
            format=format_str,
            rotation=log_rotation,
            retention=log_retention,
            serialize=serialize,
            colorize=False  # No colors in log files
        )

    logger.debug(f"Logging configured - Level: {log_level}, Format: {log_format}, JSON: {log_json}, File: {log_file}")

# Initialize logging
configure_logging()

BASE_HEADER = '''"""
AUTO-GENERATED ORM MODELS DO NOT EDIT!!!
This file was generated by sqlacodegen.
Schema is dynamically injected at runtime using DB_SCHEMA.
"""

import os
from sqlalchemy.orm import declarative_base
from sqlalchemy import MetaData

def make_base(schema: str):
    metadata = MetaData(schema=schema)
    return declarative_base(metadata=metadata)

DB_SCHEMA = os.getenv("DB_SCHEMA", "public")
Base = make_base(DB_SCHEMA)

'''


class ORMGeneratorError(Exception):
    """Custom exception for ORM generation errors."""
    pass


def create_dummy_file(filepath: Path) -> None:
    """Create a dummy file with placeholder content."""
    filepath.parent.mkdir(parents=True, exist_ok=True)

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(BASE_HEADER)
            f.write("# Replace this content with generated ORM code\n")
        logger.info(f"Dummy file created at {filepath}")
    except OSError as e:
        raise ORMGeneratorError(f"Failed to create dummy file at {filepath}: {e}") from e


def get_tables_in_schema(db_url: str, schema: Optional[str] = None) -> List[str]:
    """Retrieve the list of tables in the database schema."""
    try:
        engine = create_engine(db_url)
        metadata = MetaData()
        metadata.reflect(bind=engine)
        tables = list(metadata.tables.keys())
        logger.debug(f"Tables in schema '{schema or 'default'}': {tables}")
        return tables
    except SQLAlchemyError as e:
        raise ORMGeneratorError(f"Failed to connect to database or reflect schema: {e}") from e


def parse_comma_separated_env(env_var: str, default: str = "") -> List[str]:
    """Parse comma-separated environment variable into a list of stripped strings."""
    value = os.getenv(env_var, default)
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def filter_tables(all_tables: List[str], excluded_patterns: List[str]) -> List[str]:
    """
    Filter tables based on exclusion patterns using wildcard matching.

    Supports Unix shell-style wildcards:
    - * matches everything
    - ? matches any single character
    - [seq] matches any character in seq
    - [!seq] matches any character not in seq

    Examples:
    - "temp_*" excludes all tables starting with "temp_"
    - "*_backup" excludes all tables ending with "_backup"
    - "test_table_?" excludes test_table_1, test_table_2, etc.
    """
    if not excluded_patterns:
        logger.debug("No exclusion patterns specified, including all tables")
        return all_tables

    filtered_tables = []
    excluded_tables = []

    for table in all_tables:
        is_excluded = False

        for pattern in excluded_patterns:
            if fnmatch.fnmatch(table, pattern):
                logger.debug(f"Table '{table}' excluded by pattern '{pattern}'")
                is_excluded = True
                excluded_tables.append((table, pattern))
                break

        if not is_excluded:
            filtered_tables.append(table)

    logger.info(f"Table filtering results: {len(filtered_tables)} included, {len(excluded_tables)} excluded from {len(all_tables)} total")

    if excluded_tables:
        logger.debug("Excluded tables details:")
        for table, pattern in excluded_tables:
            logger.debug(f"  - '{table}' (pattern: '{pattern}')")

    return filtered_tables


def validate_environment() -> dict:
    """Validate required environment variables and return configuration."""
    db_url = os.getenv("DB_URL")
    if not db_url:
        raise ORMGeneratorError("DB_URL environment variable is not set")

    excluded_patterns = parse_comma_separated_env("EXCLUDED_TABLES", "spatial_ref_sys,alembic_version")

    config = {
        "db_url": db_url,
        "outfile_path": Path(os.getenv("OUTFILE_PATH", "src/fuelrod_exporter/models/fuelrod.py")),
        "excluded_tables": excluded_patterns,
        "included_views": parse_comma_separated_env("INCLUDED_VIEWS"),
        "generator": os.getenv("GENERATOR", "declarative"),
        "schema": os.getenv("DB_SCHEMA")  # Optional schema specification
    }

    logger.info("Configuration loaded:")
    logger.info(f"  - Database URL: {db_url[:20]}...")  # Truncate for security
    logger.info(f"  - Output file: {config['outfile_path']}")
    logger.info(f"  - Excluded patterns: {excluded_patterns}")
    logger.info(f"  - Included views: {config['included_views']}")
    logger.info(f"  - Generator: {config['generator']}")
    logger.info(f"  - Schema: {config['schema'] or 'default'}")

    return config


def run_sqlacodegen_command(config: dict, tables_to_include: List[str]) -> None:
    """Execute the sqlacodegen command with proper error handling."""
    command = [
        "sqlacodegen",
        config["db_url"],
        "--outfile", str(config["outfile_path"]),
        "--generator", config["generator"],
        "--tables", ",".join(tables_to_include),
    ]

    # Add schema if specified
    # if config["schema"]:
    #     command.extend(["--schema", config["schema"]])

    logger.debug(f"Executing command: {' '.join(command)}")

    try:
        result = subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True,
            timeout=300  # 5-minute timeout
        )

        if result.stdout:
            logger.debug(f"sqlacodegen stdout: {result.stdout}")
        if result.stderr:
            logger.warning(f"sqlacodegen stderr: {result.stderr}")

    except subprocess.CalledProcessError as e:
        error_msg = f"sqlacodegen failed with exit code {e.returncode}"
        if e.stderr:
            error_msg += f": {e.stderr}"
        raise ORMGeneratorError(error_msg) from e
    except subprocess.TimeoutExpired as e:
        raise ORMGeneratorError("sqlacodegen command timed out after 5 minutes") from e

def strip_sqlacodegen_header(filepath: Path) -> None:
    """Remove sqlacodegen's autogenerated Base class and header."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            lines = f.readlines()

        start_idx = 0
        for i, line in enumerate(lines):
            # stop at first model class, skip the autogenerated Base
            if line.strip().startswith("class ") and not line.strip().startswith("class Base"):
                start_idx = i
                break

        with open(filepath, "w", encoding="utf-8") as f:
            f.writelines(lines[start_idx:])

        logger.info(f"Stripped sqlacodegen Base/header from {filepath}")
    except OSError as e:
        raise ORMGeneratorError(f"Failed to strip header: {e}") from e

def prepend_header_to_file(filepath: Path) -> None:
    """Prepend the BASE_HEADER to the generated file."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(BASE_HEADER + content)

        logger.info("Header prepended to generated models file")
    except OSError as e:
        raise ORMGeneratorError(f"Failed to prepend header to {filepath}: {e}") from e


def run_sqlacodegen() -> None:
    """
    Run sqlacodegen to generate model classes with comprehensive error handling.
    """
    try:
        # Validate environment and get configuration
        config = validate_environment()

        # Create dummy file first
        create_dummy_file(config["outfile_path"])

        # Get all tables from the database
        all_tables = get_tables_in_schema(config["db_url"], config["schema"])

        if not all_tables:
            logger.warning("No tables found in the database schema")
            return

        # Filter tables based on exclusion patterns
        included_tables = filter_tables(all_tables, config["excluded_tables"])

        # Add any explicitly included views
        included_tables.extend(config["included_views"])

        # Remove duplicates while preserving order
        included_tables = list(dict.fromkeys(included_tables))

        if not included_tables:
            logger.warning("No tables/views left after applying filters")
            return

        logger.info(f"Generating models for {len(included_tables)} tables/views: {included_tables}")

        # Run sqlacodegen
        run_sqlacodegen_command(config, included_tables)

        # Prepend header to generated file
        path = config["outfile_path"]
        # strip_sqlacodegen_header(path)
        prepend_header_to_file(path)

        logger.success("ORM models generated successfully!")

    except Exception as e:
        logger.error(f"Unexpected error during ORM generation: {e}")
        raise ORMGeneratorError(f"Unexpected error: {e}") from e


if __name__ == "__main__":
    try:
        run_sqlacodegen()
    except ORMGeneratorError:
        exit(1)
    except KeyboardInterrupt:
        logger.info("Operation cancelled by user")
        exit(130)