[supervisord]
nodaemon=false
# user=root
logfile=/app/logs/supervisord.log
loglevel=info
# pidfile=/app/logs/supervisord.pid

[include]
files = /etc/supervisor/conf.d/*.conf

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock