"""
AUTO-GENERATED ORM VIEW MODELS REWRITTEN AS CLASSES
This file was generated by ViewClassWriter.
"""
from typing import Any
from datetime import datetime
from sqlalchemy.orm import Mapped, mapped_column, declarative_base
from sqlalchemy import String, Text, BigInteger, Boolean, Numeric, Sequence
from sqlalchemy.dialects.postgresql import TIMESTAMP

Base = declarative_base()
class SmsReport(Base):
    __tablename__ = 'vw_sms_reports'

    id: Mapped[int] = mapped_column(BigInteger())
    api_account_id: Mapped[int] = mapped_column(BigInteger())
    message_id: Mapped[str] = mapped_column(String(length=255))
    campaign_id: Mapped[int] = mapped_column(BigInteger())
    campaign_message_id: Mapped[int] = mapped_column(BigInteger())
    sender_id: Mapped[str] = mapped_column(String(length=11))
    phone_number: Mapped[str] = mapped_column(String(length=150))
    network_identity: Mapped[str] = mapped_column(String(length=255))
    message: Mapped[str] = mapped_column(Text())
    network_name: Mapped[str] = mapped_column(String(length=255))
    sms_count: Mapped[int] = mapped_column(BigInteger())
    character_count: Mapped[int] = mapped_column(BigInteger())
    single_sms_cost: Mapped[float] = mapped_column(Numeric(precision=10, scale=2))
    actual_cost: Mapped[float] = mapped_column(Numeric(precision=10, scale=2))
    delivery_status: Mapped[str] = mapped_column(String(length=120))
    delivered_to_handset: Mapped[bool] = mapped_column(Boolean())
    sent_to_network: Mapped[bool] = mapped_column(Boolean())
    description: Mapped[str] = mapped_column(String())
    message_archived: Mapped[bool] = mapped_column(Boolean())
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True, precision=0))
    updated_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True, precision=0))
