"""
AUTO-GENERATED ORM MODELS DO NOT EDIT!!!
This file was generated by sqlacodegen.
Schema is dynamically injected at runtime using DB_SCHEMA.
"""

import os
from sqlalchemy.orm import declarative_base
from sqlalchemy import MetaData

def make_base(schema: str):
    metadata = MetaData(schema=schema)
    return declarative_base(metadata=metadata)

DB_SCHEMA = os.getenv("DB_SCHEMA", "public")
Base = make_base(DB_SCHEMA)

from typing import Optional
import datetime
import decimal

from sqlalchemy import BigInteger, Boolean, Computed, Date, DateTime, ForeignKeyConstraint, Index, Integer, JSON, Numeric, PrimaryKeyConstraint, Sequence, SmallInteger, String, Text, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

class Base(DeclarativeBase):
    pass


class ApiAccounts(Base):
    __tablename__ = 'api_accounts'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='idx_17043_primary'),
        Index('idx_17043_user_name', 'username', unique=True),
        Index('idx_17043_user_uuid_uk', 'uuid', unique=True)
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    uuid: Mapped[str] = mapped_column(String(64), nullable=False)
    account_type: Mapped[str] = mapped_column(String(15), nullable=False, server_default=text("'CLIENT'::character varying"))
    role: Mapped[str] = mapped_column(String(8), nullable=False, server_default=text("'USER'::character varying"))
    username: Mapped[Optional[str]] = mapped_column(String(18), server_default=text('NULL::character varying'))
    threshold_amount: Mapped[Optional[decimal.Decimal]] = mapped_column(Numeric(10, 2), server_default=text('0.00'))
    alert_enabled: Mapped[Optional[bool]] = mapped_column(Boolean, server_default=text('false'))
    name: Mapped[Optional[str]] = mapped_column(String(200), server_default=text('NULL::character varying'))
    email: Mapped[Optional[str]] = mapped_column(String(50), server_default=text('NULL::character varying'))
    password: Mapped[Optional[str]] = mapped_column(String(200), server_default=text('NULL::character varying'))
    message_cost: Mapped[Optional[decimal.Decimal]] = mapped_column(Numeric(10, 2), server_default=text('1.50'))
    queue_message: Mapped[Optional[bool]] = mapped_column(Boolean)
    overdraft: Mapped[Optional[bool]] = mapped_column(Boolean)
    enabled: Mapped[Optional[bool]] = mapped_column(Boolean)
    account_status: Mapped[Optional[str]] = mapped_column(String(50), server_default=text('NULL::character varying'))
    reason: Mapped[Optional[str]] = mapped_column(Text, comment='Provide reason for setting a status other than ACTIVE')
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))

    api_service: Mapped[list['ApiService']] = relationship('ApiService', back_populates='api_account')
    fee_endpoints: Mapped[list['FeeEndpoints']] = relationship('FeeEndpoints', back_populates='api_accounts')
    payments: Mapped[list['Payments']] = relationship('Payments', back_populates='api_account')
    sms_campaign: Mapped[list['SmsCampaign']] = relationship('SmsCampaign', back_populates='api_account')
    sms_credit_balances: Mapped['SmsCreditBalances'] = relationship('SmsCreditBalances', uselist=False, back_populates='api_account')
    sms_statistics: Mapped[list['SmsStatistics']] = relationship('SmsStatistics', back_populates='user')
    user_alerts: Mapped[list['UserAlerts']] = relationship('UserAlerts', back_populates='api_account')
    user_api_account: Mapped[list['UserApiAccount']] = relationship('UserApiAccount', back_populates='account')
    sms_outbox: Mapped[list['SmsOutbox']] = relationship('SmsOutbox', back_populates='api_account')


class ApiCredentials(Base):
    __tablename__ = 'api_credentials'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='idx_17062_primary'),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    service_name: Mapped[str] = mapped_column(String(50), nullable=False)
    api_user: Mapped[str] = mapped_column(String(50), nullable=False)
    api_key: Mapped[str] = mapped_column(Text, nullable=False)
    endpoint: Mapped[str] = mapped_column(String(100), nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('CURRENT_TIMESTAMP'))
    use_default_sender: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text('false'), comment='Use default sender')
    default_sender: Mapped[Optional[str]] = mapped_column(String(11), server_default=text('NULL::character varying'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True))

    api_service: Mapped[list['ApiService']] = relationship('ApiService', back_populates='api_credentials')


class AppReleases(Base):
    __tablename__ = 'app_releases'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='app_releases_pkey'),
        UniqueConstraint('app_name', name='app_releases_app_name_unique')
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    app_name: Mapped[str] = mapped_column(String(255), nullable=False)
    build_number: Mapped[int] = mapped_column(BigInteger, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(TIMESTAMP(True, 0), nullable=False, server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0))


class IncomingMessage(Base):
    __tablename__ = 'incoming_message'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='idx_17141_primary'),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    message_id: Mapped[str] = mapped_column(String(200), nullable=False)
    link_id: Mapped[str] = mapped_column(String(200), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    short_code: Mapped[str] = mapped_column(String(50), nullable=False)
    phone_number: Mapped[str] = mapped_column(String(30), nullable=False)
    date_sent: Mapped[Optional[str]] = mapped_column(String(30), server_default=text('NULL::character varying'))
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))


class MobileNetworks(Base):
    __tablename__ = 'mobile_networks'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='mobile_networks_pkey1'),
        UniqueConstraint('country_code', 'plmn_code', name='country_plmn_unique'),
        UniqueConstraint('network_identity', name='mobile_networks_network_identity_unique'),
        Index('mobile_networks_country_code_index', 'country_code'),
        Index('mobile_networks_country_name_index', 'country_name'),
        Index('mobile_networks_mobile_country_code_index', 'mobile_country_code'),
        Index('mobile_networks_mobile_network_code_index', 'mobile_network_code'),
        Index('mobile_networks_network_name_index', 'network_name'),
        Index('mobile_networks_plmn_code_index', 'plmn_code')
    )

    id: Mapped[int] = mapped_column(BigInteger, Sequence('mobile_networks_id_seq1'), primary_key=True)
    mobile_country_code: Mapped[int] = mapped_column(BigInteger, nullable=False, comment='Mobile Country Code (MCC), a 3-digit code that identifies the country of the mobile network')
    mobile_network_code: Mapped[int] = mapped_column(BigInteger, nullable=False, comment='Mobile Network Code (MNC), a 2- or 3-digit code that identifies the specific network within the MCC')
    plmn_code: Mapped[int] = mapped_column(BigInteger, nullable=False, comment='Public Land Mobile Network (PLMN) code, formed by concatenating MCC and MNC (e.g., 63902 for Safaricom)')
    network_identity: Mapped[str] = mapped_column(String(20), Computed("(((country_code)::text || '-'::text) || plmn_code)", persisted=True), nullable=False)
    country_name: Mapped[str] = mapped_column(String(100), nullable=False, comment='Full name of the country where the network is registered')
    country_code: Mapped[str] = mapped_column(String(20), nullable=False, comment='ISO 3166-1 alpha-2 country code (e.g., KE for Kenya)')
    geographic_region: Mapped[Optional[str]] = mapped_column(String(50), comment='Continent or broad geographic region where the network operates (e.g., Africa, Asia)')
    operator_name: Mapped[Optional[str]] = mapped_column(String(255), comment='Legal or corporate name of the mobile network operator')
    network_name: Mapped[Optional[str]] = mapped_column(String(50), comment='Consumer-facing or marketing name of the mobile network')
    tadig_roaming_code: Mapped[Optional[str]] = mapped_column(String(10), comment='TADIG code used in GSM roaming agreements and billing records (e.g., SAFK)')
    frequency_bands: Mapped[Optional[str]] = mapped_column(Text, comment='Network frequency bands and technologies used (e.g., GSM 900, LTE B3, 5G NR)')

    sms_outbox: Mapped[list['SmsOutbox']] = relationship('SmsOutbox', back_populates='mobile_networks')


class OptedOut(Base):
    __tablename__ = 'opted_out'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='idx_17241_primary'),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    sender_id: Mapped[Optional[str]] = mapped_column(String(15), server_default=text('NULL::character varying'))
    phone_number: Mapped[Optional[str]] = mapped_column(String(25), server_default=text('NULL::character varying'))
    counter: Mapped[Optional[int]] = mapped_column(BigInteger, server_default=text("'1'::bigint"))
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))


class RemoteConfig(Base):
    __tablename__ = 'remote_config'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='idx_17324_primary'),
        Index('idx_17324_config-name-uk', 'app_name', 'config_name', unique=True),
        {'comment': 'Table to store remote configuration options'}
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    app_name: Mapped[str] = mapped_column(String(50), nullable=False)
    config_name: Mapped[str] = mapped_column(String(50), nullable=False)
    config_value: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))


class SentEmails(Base):
    __tablename__ = 'sent_emails'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='sent_emails_pkey'),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    subject: Mapped[str] = mapped_column(String(255), nullable=False)
    payload_json: Mapped[dict] = mapped_column(JSON, nullable=False)
    recipient: Mapped[str] = mapped_column(String(100), nullable=False)
    mailable_class: Mapped[str] = mapped_column(String(255), nullable=False)
    success: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text('false'))
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text('1'))
    sent_at: Mapped[datetime.datetime] = mapped_column(TIMESTAMP(True, 0), nullable=False, server_default=text('CURRENT_TIMESTAMP'))
    error_message: Mapped[Optional[str]] = mapped_column(Text)
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0), server_default=text('CURRENT_TIMESTAMP'))


class SmsCreditBalance(Base):
    __tablename__ = 'sms_credit_balance'
    __table_args__ = (
        PrimaryKeyConstraint('api_account_id', name='sms_credit_balance_pkey'),
    )

    api_account_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    used_credits: Mapped[decimal.Decimal] = mapped_column(Numeric(15, 3), nullable=False, server_default=text("'0'::numeric"))
    historical_used_credits: Mapped[decimal.Decimal] = mapped_column(Numeric(15, 3), nullable=False, server_default=text("'0'::numeric"))
    total_purchased_credits: Mapped[decimal.Decimal] = mapped_column(Numeric(15, 3), nullable=False, server_default=text("'0'::numeric"))
    legacy_imported_credits: Mapped[decimal.Decimal] = mapped_column(Numeric(15, 3), nullable=False, server_default=text("'0'::numeric"))
    available_credits: Mapped[decimal.Decimal] = mapped_column(Numeric(15, 3), nullable=False, server_default=text("'0'::numeric"))
    running_credits: Mapped[decimal.Decimal] = mapped_column(Numeric(10, 3), nullable=False, server_default=text("'0'::numeric"))
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0), server_default=text('CURRENT_TIMESTAMP'))


class UntrackedCallback(Base):
    __tablename__ = 'untracked_callback'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='idx_17419_primary'),
        {'comment': 'Table to track unsaved callbacks'}
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    message_id: Mapped[str] = mapped_column(String(250), nullable=False, comment='message identifier')
    network_code: Mapped[Optional[str]] = mapped_column(String(50), server_default=text('NULL::character varying'))
    phone_number: Mapped[Optional[str]] = mapped_column(String(100), server_default=text('NULL::character varying'))
    message_status: Mapped[Optional[str]] = mapped_column(String(100), server_default=text('NULL::character varying'))
    retry_count: Mapped[Optional[int]] = mapped_column(BigInteger)
    failure_reason: Mapped[Optional[str]] = mapped_column(String(100), server_default=text('NULL::character varying'))
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))


class Users(Base):
    __tablename__ = 'users'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='idx_17432_primary'),
        Index('idx_17432_user_email', 'email', unique=True),
        Index('idx_17432_user_name', 'username', unique=True),
        {'comment': 'Table to store account users'}
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    username: Mapped[str] = mapped_column(String(18), nullable=False)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    receive_email: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text('false'))
    password: Mapped[str] = mapped_column(String(255), nullable=False)
    change_password: Mapped[bool] = mapped_column(Boolean, nullable=False)
    account_status: Mapped[str] = mapped_column(String(100), nullable=False, server_default=text("'ACTIVE'::character varying"))
    active: Mapped[bool] = mapped_column(Boolean, nullable=False)
    receive_credit_alert: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text('false'))
    email: Mapped[Optional[str]] = mapped_column(String(50), server_default=text('NULL::character varying'))
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))

    user_api_account: Mapped[list['UserApiAccount']] = relationship('UserApiAccount', back_populates='user')


class ApiService(Base):
    __tablename__ = 'api_service'
    __table_args__ = (
        ForeignKeyConstraint(['api_account_id'], ['api_accounts.id'], ondelete='RESTRICT', onupdate='CASCADE', name='fk-api-account-id-config'),
        ForeignKeyConstraint(['api_credentials_id'], ['api_credentials.id'], ondelete='SET NULL', onupdate='CASCADE', name='fk_api_service_api_credentials_id'),
        PrimaryKeyConstraint('id', name='idx_17081_primary'),
        Index('idx_17081_fk-api-account-id-config', 'api_account_id'),
        Index('idx_17081_fk_api_service_api_credentials_id', 'api_credentials_id')
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    api_account_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    service: Mapped[str] = mapped_column(String(20), nullable=False)
    service_type: Mapped[str] = mapped_column(String(10), nullable=False)
    sender: Mapped[str] = mapped_column(String(11), nullable=False)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text('true'))
    api_credentials_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))

    api_account: Mapped['ApiAccounts'] = relationship('ApiAccounts', back_populates='api_service')
    api_credentials: Mapped[Optional['ApiCredentials']] = relationship('ApiCredentials', back_populates='api_service')


class FeeEndpoints(Base):
    __tablename__ = 'fee_endpoints'
    __table_args__ = (
        ForeignKeyConstraint(['username'], ['api_accounts.username'], ondelete='RESTRICT', onupdate='RESTRICT', name='fk-endpoint-username'),
        PrimaryKeyConstraint('id', name='idx_17134_primary'),
        Index('idx_17134_uk-endpoint-username', 'username', unique=True)
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    username: Mapped[str] = mapped_column(String(18), nullable=False)
    data_endpoint: Mapped[str] = mapped_column(String(120), nullable=False)
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))

    api_accounts: Mapped['ApiAccounts'] = relationship('ApiAccounts', back_populates='fee_endpoints')


class Payments(Base):
    __tablename__ = 'payments'
    __table_args__ = (
        ForeignKeyConstraint(['api_account_id'], ['api_accounts.id'], ondelete='CASCADE', onupdate='CASCADE', name='fk_api_account_id'),
        PrimaryKeyConstraint('id', name='payments_pkey'),
        UniqueConstraint('payment_ref', name='uk-payment-ref'),
        Index('idx-credit-amount', 'credit_amount'),
        {'comment': 'Table to track user SMS credit top ups'}
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    api_account_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    payment_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    payment_ref: Mapped[str] = mapped_column(String(255), nullable=False)
    credit_amount: Mapped[decimal.Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    tax_amount: Mapped[decimal.Decimal] = mapped_column(Numeric(10, 3), nullable=False, server_default=text("'0'::numeric"))
    total_paid: Mapped[decimal.Decimal] = mapped_column(Numeric(10, 3), nullable=False, server_default=text("'0'::numeric"))
    narration: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0), server_default=text('CURRENT_TIMESTAMP'))

    api_account: Mapped['ApiAccounts'] = relationship('ApiAccounts', back_populates='payments')


class SmsCampaign(Base):
    __tablename__ = 'sms_campaign'
    __table_args__ = (
        ForeignKeyConstraint(['api_account_id'], ['api_accounts.id'], ondelete='RESTRICT', onupdate='CASCADE', name='fk_campaign_api_account_id'),
        PrimaryKeyConstraint('id', name='idx_17353_primary'),
        Index('idx_17353_fk_campaign_api_account_id', 'api_account_id'),
        Index('idx_17353_idx-campaign-status', 'campaign_status'),
        Index('idx_17353_sms_campaign_is_expired_index', 'is_expired')
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    api_account_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    campaign_name: Mapped[str] = mapped_column(String(255), nullable=False)
    is_expired: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text('false'))
    campaign_status: Mapped[Optional[str]] = mapped_column(String(100), server_default=text('NULL::character varying'))
    is_draft: Mapped[Optional[bool]] = mapped_column(Boolean)
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))

    api_account: Mapped['ApiAccounts'] = relationship('ApiAccounts', back_populates='sms_campaign')
    message_queue: Mapped[list['MessageQueue']] = relationship('MessageQueue', back_populates='campaign')


class SmsCreditBalances(Base):
    __tablename__ = 'sms_credit_balances'
    __table_args__ = (
        ForeignKeyConstraint(['api_account_id'], ['api_accounts.id'], ondelete='CASCADE', onupdate='CASCADE', name='sms_credit_balances_api_account_id_foreign'),
        PrimaryKeyConstraint('id', name='sms_credit_balances_pkey'),
        UniqueConstraint('api_account_id', name='uk-api-account-sms-balance')
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    api_account_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    purchased_credits: Mapped[decimal.Decimal] = mapped_column(Numeric(18, 3), nullable=False, server_default=text("'0'::numeric"))
    legacy_credits: Mapped[decimal.Decimal] = mapped_column(Numeric(18, 3), nullable=False, server_default=text("'0'::numeric"))
    current_usage: Mapped[decimal.Decimal] = mapped_column(Numeric(18, 3), nullable=False, server_default=text("'0'::numeric"))
    archived_usage: Mapped[decimal.Decimal] = mapped_column(Numeric(18, 3), nullable=False, server_default=text("'0'::numeric"))
    available_credits: Mapped[decimal.Decimal] = mapped_column(Numeric(18, 3), nullable=False, server_default=text("'0'::numeric"))
    running_credits: Mapped[decimal.Decimal] = mapped_column(Numeric(18, 3), nullable=False, server_default=text("'0'::numeric"))
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0))

    api_account: Mapped['ApiAccounts'] = relationship('ApiAccounts', back_populates='sms_credit_balances')


class SmsStatistics(Base):
    __tablename__ = 'sms_statistics'
    __table_args__ = (
        ForeignKeyConstraint(['user_id'], ['api_accounts.id'], ondelete='RESTRICT', onupdate='RESTRICT', name='fk-sms-stats-user-id'),
        PrimaryKeyConstraint('id', name='idx_17399_primary'),
        Index('idx_17399_fk-sms-stats-user-id', 'user_id'),
        Index('idx_17399_idx-message-date', 'message_date'),
        Index('idx_17399_idx-message-end-date', 'message_end_date'),
        Index('idx_17399_idx-message-start-date', 'message_start_date'),
        Index('idx_17399_idx-total-cost', 'total_cost'),
        Index('idx_17399_idx-total-messages', 'total_messages'),
        Index('idx_17399_idx-total-recipients', 'total_recipients'),
        {'comment': 'Table to store sms statistics'}
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    user_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    is_campaign: Mapped[bool] = mapped_column(Boolean, nullable=False)
    sender_id: Mapped[str] = mapped_column(String(11), nullable=False)
    total_recipients: Mapped[int] = mapped_column(BigInteger, nullable=False)
    total_cost: Mapped[decimal.Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    total_messages: Mapped[int] = mapped_column(BigInteger, nullable=False)
    message_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    message_start_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    message_end_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)

    user: Mapped['ApiAccounts'] = relationship('ApiAccounts', back_populates='sms_statistics')


class UserAlerts(Base):
    __tablename__ = 'user_alerts'
    __table_args__ = (
        ForeignKeyConstraint(['api_account_id'], ['api_accounts.id'], ondelete='CASCADE', onupdate='CASCADE', name='idx_user_alerts_api_account_id'),
        PrimaryKeyConstraint('id', name='user_alerts_pkey'),
        Index('idx_user_alerts_created_at', 'created_at'),
        Index('idx_user_alerts_updated_at', 'updated_at')
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    recipient_name: Mapped[str] = mapped_column(String(150), nullable=False)
    email: Mapped[str] = mapped_column(String(50), nullable=False)
    receive_credit_alert: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text('true'))
    receive_sms_reports: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text('true'))
    api_account_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    phone_number: Mapped[Optional[str]] = mapped_column(String(20))
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0))

    api_account: Mapped[Optional['ApiAccounts']] = relationship('ApiAccounts', back_populates='user_alerts')


class UserApiAccount(Base):
    __tablename__ = 'user_api_account'
    __table_args__ = (
        ForeignKeyConstraint(['account_id'], ['api_accounts.id'], ondelete='CASCADE', onupdate='RESTRICT', name='fk_api_account_api_id'),
        ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE', onupdate='RESTRICT', name='fk_api_account_user_id'),
        PrimaryKeyConstraint('id', name='idx_17444_primary'),
        Index('idx_17444_fk_api_account_api_id', 'account_id'),
        Index('idx_17444_fk_user_id_account_id', 'user_id', 'account_id', unique=True),
        {'comment': 'Junction table for user accounts and api accounts for easier '
                'management'}
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    user_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    account_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('CURRENT_TIMESTAMP'))

    account: Mapped[Optional['ApiAccounts']] = relationship('ApiAccounts', back_populates='user_api_account')
    user: Mapped[Optional['Users']] = relationship('Users', back_populates='user_api_account')


class MessageQueue(Base):
    __tablename__ = 'message_queue'
    __table_args__ = (
        ForeignKeyConstraint(['campaign_id'], ['sms_campaign.id'], ondelete='CASCADE', onupdate='CASCADE', name='message-queue-campaign-id-fk'),
        PrimaryKeyConstraint('id', name='message_queue_pkey'),
        Index('fk-campaign-id', 'campaign_id'),
        Index('idx-message-queue-hash', 'message_hash'),
        Index('idx-phone-number', 'phone_number')
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    campaign_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    message_length: Mapped[int] = mapped_column(Integer, nullable=False)
    retry_count: Mapped[Optional[int]] = mapped_column(Integer)
    message_hash: Mapped[Optional[str]] = mapped_column(String(150))
    message_status: Mapped[Optional[str]] = mapped_column(String(100))
    failure_reason: Mapped[Optional[str]] = mapped_column(String(100))
    phone_number: Mapped[Optional[str]] = mapped_column(String(150))
    number_valid: Mapped[Optional[int]] = mapped_column(SmallInteger)
    sms_count: Mapped[Optional[int]] = mapped_column(Integer)
    message_cost: Mapped[Optional[decimal.Decimal]] = mapped_column(Numeric(10, 2))
    message_sent: Mapped[Optional[int]] = mapped_column(SmallInteger)
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(precision=6))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(precision=6))

    campaign: Mapped['SmsCampaign'] = relationship('SmsCampaign', back_populates='message_queue')
    sms_outbox: Mapped[list['SmsOutbox']] = relationship('SmsOutbox', back_populates='campaign_message')


class SmsOutbox(Base):
    __tablename__ = 'sms_outbox'
    __table_args__ = (
        ForeignKeyConstraint(['api_account_id'], ['api_accounts.id'], ondelete='RESTRICT', onupdate='RESTRICT', name='fk-outbox-api-account-id'),
        ForeignKeyConstraint(['campaign_message_id'], ['message_queue.id'], ondelete='CASCADE', onupdate='CASCADE', name='fk-campaign-message-id'),
        ForeignKeyConstraint(['network_identity'], ['mobile_networks.network_identity'], ondelete='RESTRICT', onupdate='CASCADE', name='fk-mobile-networks-identity'),
        PrimaryKeyConstraint('id', name='sms_outbox_pkey'),
        Index('ftx_sms_outbox_message_hash'),
        Index('idx_sms_outbox_actual_cost', 'actual_cost'),
        Index('idx_sms_outbox_api_account_id', 'api_account_id'),
        Index('idx_sms_outbox_campaign_message_id', 'campaign_message_id'),
        Index('idx_sms_outbox_created_at', 'created_at'),
        Index('idx_sms_outbox_currency', 'currency'),
        Index('idx_sms_outbox_delivery_status', 'delivery_status'),
        Index('idx_sms_outbox_filter', 'api_account_id', 'is_campaign', 'archive_message'),
        Index('idx_sms_outbox_message_id', 'message_id'),
        Index('idx_sms_outbox_network_identity', 'network_identity')
    )

    id: Mapped[int] = mapped_column(BigInteger, Sequence('sms_outbox_id_seq1'), primary_key=True)
    is_campaign: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text('false'))
    archive_message: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text('false'))
    requeue_message: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text('false'))
    sender_id: Mapped[str] = mapped_column(String(11), nullable=False)
    network_identity: Mapped[str] = mapped_column(String(255), nullable=False, server_default=text("'ZZ-0'::character varying"))
    sms_text: Mapped[str] = mapped_column(Text, nullable=False)
    character_count: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default=text("'160'::bigint"))
    sms_count: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default=text("'1'::bigint"))
    single_sms_cost: Mapped[decimal.Decimal] = mapped_column(Numeric(10, 2), nullable=False, server_default=text("'2'::numeric"))
    currency: Mapped[str] = mapped_column(String(4), nullable=False, server_default=text("'KES'::character varying"))
    currency_rate: Mapped[decimal.Decimal] = mapped_column(Numeric(10, 2), nullable=False, server_default=text("'1'::numeric"))
    delivery_status: Mapped[str] = mapped_column(String(120), nullable=False)
    message_delivered: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text('false'))
    retry_count: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default=text("'0'::bigint"))
    api_account_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    campaign_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    campaign_message_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    message_hash: Mapped[Optional[str]] = mapped_column(String(150))
    message_id: Mapped[Optional[str]] = mapped_column(String(255))
    phone_number: Mapped[Optional[str]] = mapped_column(String(150))
    encoding_type: Mapped[Optional[str]] = mapped_column(String(20))
    message_string_cost: Mapped[Optional[str]] = mapped_column(String(25))
    message_cost: Mapped[Optional[decimal.Decimal]] = mapped_column(Numeric(10, 2))
    actual_cost: Mapped[Optional[decimal.Decimal]] = mapped_column(Numeric(10, 2))
    delivery_description: Mapped[Optional[str]] = mapped_column(Text)
    failure_reason: Mapped[Optional[str]] = mapped_column(String(255))
    date_time: Mapped[Optional[str]] = mapped_column(String(100))
    expires_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0))
    created_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0), server_default=text('CURRENT_TIMESTAMP'))
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(True, 0), server_default=text('CURRENT_TIMESTAMP'))

    api_account: Mapped[Optional['ApiAccounts']] = relationship('ApiAccounts', back_populates='sms_outbox')
    campaign_message: Mapped[Optional['MessageQueue']] = relationship('MessageQueue', back_populates='sms_outbox')
    mobile_networks: Mapped['MobileNetworks'] = relationship('MobileNetworks', back_populates='sms_outbox')
