"""
AUTO-GENERATED ORM MODELS DO NOT EDIT!!!
This file was generated by sqlacodegen.
Schema is dynamically injected at runtime using DB_SCHEMA.
"""

import os
from sqlalchemy.orm import declarative_base
from sqlalchemy import MetaData

def make_base(schema: str):
    metadata = MetaData(schema=schema)
    return declarative_base(metadata=metadata)

DB_SCHEMA = os.getenv("DB_SCHEMA", "public")
Base = make_base(DB_SCHEMA)

from sqlalchemy import BigInteger, Boolean, Column, Index, MetaData, Numeric, String, Table, Text
from sqlalchemy.dialects.postgresql import TIMESTAMP

metadata = MetaData()


t_vw_sms_reports = Table(
    'vw_sms_reports', metadata,
    Column('pk_id', BigInteger),
    Column('id', BigInteger),
    Column('api_account_id', BigInteger),
    Column('message_id', String(255)),
    Column('campaign_id', BigInteger),
    Column('campaign_message_id', BigInteger),
    Column('sender_id', String(11)),
    Column('phone_number', String(150)),
    Column('network_identity', String(255)),
    Column('message', Text),
    Column('network_name', String(255)),
    Column('sms_count', BigInteger),
    Column('character_count', BigInteger),
    Column('single_sms_cost', Numeric(10, 2)),
    Column('actual_cost', Numeric(10, 2)),
    Column('delivery_status', String(120)),
    Column('delivered_to_handset', Boolean),
    Column('sent_to_network', Boolean),
    Column('description', String),
    Column('message_archived', Boolean),
    Column('created_at', TIMESTAMP(True, 0)),
    Column('updated_at', TIMESTAMP(True, 0)),
    Index('vw_sms_reports_pk', 'pk_id', unique=True)
)
