import os
from pathlib import Path
from sqlalchemy import (
    Table, Column, MetaData, BigInteger, Boolean, Numeric, String, Text, Sequence
)
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlalchemy.orm import Mapped, mapped_column, declarative_base


class ViewClassWriter:
    @staticmethod
    def parse_generated_file(path: str):
        """
        Execute the generated view file and collect all Table objects.
        """
        namespace = {
            "Table": Table,
            "Column": Column,
            "MetaData": MetaData,
            "BigInteger": BigInteger,
            "Boolean": Boolean,
            "Numeric": Numeric,
            "String": String,
            "Text": Text,
            "TIMESTAMP": TIMESTAMP,
            "Sequence": Sequence,
        }

        with open(path, "r", encoding="utf-8") as f:
            code = f.read()
        exec(code, namespace, namespace)

        return [obj for obj in namespace.values() if isinstance(obj, Table)]

    @staticmethod
    def _python_type(col) -> str:
        """ Map SQLAlchemy column types to Python typing hints. """
        if isinstance(col.type, BigInteger):
            return "int"
        if isinstance(col.type, Boolean):
            return "bool"
        if isinstance(col.type, String) or isinstance(col.type, Text):
            return "str"
        if isinstance(col.type, Numeric):
            return "float"
        if isinstance(col.type, TIMESTAMP):
            return "datetime"
        return "Any"

    @staticmethod
    def generate_class_code(base_name: str, table: Table) -> str:
        """ Generate ORM class code from a Table definition using Mapped[] + mapped_column(). """
        class_name = "".join([part.capitalize() for part in table.name.split("_")])
        lines = []
        lines.append(f"class {class_name}({base_name}):")
        lines.append(f"    __tablename__ = '{table.name}'")
        lines.append("")

        for col in table.columns:
            py_type = ViewClassWriter._python_type(col)
            args = [repr(col.type)]
            kwargs = []

            if col.primary_key:
                kwargs.append("primary_key=True")
            if not col.nullable:
                kwargs.append("nullable=False")
            if col.default is not None:
                kwargs.append(f"server_default={repr(col.default.arg)}")

            args_str = ", ".join(args + kwargs)
            lines.append(
                f"    {col.name}: Mapped[{py_type}] = mapped_column({args_str})"
            )

        return "\n".join(lines) + "\n"

    @staticmethod
    def rewrite_file(generated_file: str, output_file: str):
        """ Convert all Table definitions in `generated_file` into ORM class-based entities. """
        tables = ViewClassWriter.parse_generated_file(generated_file)
        classes = [ViewClassWriter.generate_class_code("Base", t) for t in tables]

        header = '''"""
AUTO-GENERATED ORM VIEW MODELS REWRITTEN AS CLASSES
This file was generated by ViewClassWriter.
"""
from typing import Any
from datetime import datetime
from sqlalchemy.orm import Mapped, mapped_column, declarative_base
from sqlalchemy import String, Text, BigInteger, Boolean, Numeric, Sequence
from sqlalchemy.dialects.postgresql import TIMESTAMP

Base = declarative_base()
'''

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(header + "\n\n".join(classes))


if __name__ == "__main__":
    # Example usage
    input_path = "app/models/generated_views.py"   # <- sqlacodegen output file
    output_path = "app/models/view_entities.py"    # <- rewritten ORM classes
    ViewClassWriter.rewrite_file(input_path, output_path)
    print(f"Rewritten classes saved to {output_path}")
