import os
from pathlib import Path
from typing import Iterator, List, Iterable, Any

from sqlalchemy import (
    Table, Column, MetaData, BigInteger, Boolean, Numeric, String, Text, Sequence
)
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlalchemy.orm import Mapped, mapped_column, declarative_base
import inflect
from sqlalchemy.sql.base import ReadOnlyColumnCollection

p = inflect.engine()


class ViewClassWriter:
    @staticmethod
    def parse_generated_file(path: str):
        """
        Execute the generated view file and collect all Table objects.
        """
        namespace = {
            "Table": Table,
            "Column": Column,
            "MetaData": MetaData,
            "BigInteger": BigInteger,
            "Boolean": Boolean,
            "Numeric": Numeric,
            "String": String,
            "Text": Text,
            "TIMESTAMP": TIMESTAMP,
            "Sequence": Sequence,
        }

        with open(path, "r", encoding="utf-8") as f:
            code = f.read()
        exec(code, namespace, namespace)

        return [obj for obj in namespace.values() if isinstance(obj, Table)]

    @staticmethod
    def _python_type(col) -> str:
        """ Map SQLAlchemy column types to Python typing hints. """
        if isinstance(col.type, BigInteger):
            return "int"
        if isinstance(col.type, Boolean):
            return "bool"
        if isinstance(col.type, String) or isinstance(col.type, Text):
            return "str"
        if isinstance(col.type, Numeric):
            return "float"
        if isinstance(col.type, TIMESTAMP):
            return "datetime"
        return "Any"

    @staticmethod
    def _make_class_name(table_name: str) -> str:
        raw_name:str = table_name

        # strip "vw_" or "vw" prefix (case-insensitive)
        if raw_name.lower().startswith("vw_"):
            raw_name = raw_name[3:]
        elif raw_name.lower().startswith("vw"):
            raw_name = raw_name[2:]

        parts: list[str] = raw_name.split("_")

        # singularize the last part if plural
        if parts:
            singular = p.singular_noun(parts[-1])
            if singular:
                parts[-1] = singular

        # build class name
        return "".join([part.capitalize() for part in parts])

    # noinspection PyTypeChecker
    @staticmethod
    def generate_class_code(base_name: str, table: Table) -> str:
        raw_name: str = table.name
        class_name: str = ViewClassWriter._make_class_name(table_name=raw_name)

        lines: List[str] = [
            f"class {class_name}({base_name}):",
            f"    __tablename__ = '{table.name}'",
            ""
        ]

        columns: ReadOnlyColumnCollection[str, Column[Any]] = table.columns  # ✅ precise

        for col in columns:  # type: Column
            py_type: str = ViewClassWriter._python_type(col)

            args: List[str] = [repr(col.type)]
            kwargs: List[str] = []

            if col.primary_key:
                kwargs.append("primary_key=True")
            if not col.nullable:
                kwargs.append("nullable=False")
            if col.default is not None:
                kwargs.append(f"server_default={repr(col.default.arg)}")

            args_str: str = ", ".join(args + kwargs)
            lines.append(
                f"    {col.name}: Mapped[{py_type}] = mapped_column({args_str})"
            )

        return "\n".join(lines) + "\n"

    @staticmethod
    def rewrite_file(generated_file: str, output_file: str):
        """ Convert all Table definitions in `generated_file` into ORM class-based entities. """
        tables = ViewClassWriter.parse_generated_file(generated_file)
        classes = [ViewClassWriter.generate_class_code("Base", t) for t in tables]

        header = '''"""
AUTO-GENERATED ORM VIEW MODELS REWRITTEN AS CLASSES
This file was generated by ViewClassWriter.
"""
from typing import Any
from datetime import datetime
from sqlalchemy.orm import Mapped, mapped_column, declarative_base
from sqlalchemy import String, Text, BigInteger, Boolean, Numeric, Sequence
from sqlalchemy.dialects.postgresql import TIMESTAMP

Base = declarative_base()
'''

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(header + "\n\n".join(classes))


if __name__ == "__main__":
    # Example usage
    input_path = "app/models/generated_views.py"  # <- sqlacodegen output file
    output_path = "app/models/view_entities.py"  # <- rewritten ORM classes
    ViewClassWriter.rewrite_file(input_path, output_path)
    print(f"Rewritten classes saved to {output_path}")
